# DispatchBatchThread will be executed after x seconds.
batch-execution-interval: 2
# will update the batch container in the DispatchBatchThread after x seconds.
batch-update-interval: 2
# Set the maximum SQLRequests per batch, will create a new batch and execute it in another DispatchBatchThread on execution.
request-per-batch: 20